Comics/urls.py
from django.urls import path
from . import views

app_name = 'Comics'

urlpatterns = [
    path('', views.index, name="index"),

    path('chapter/<str:str>/', views.chapter, name='chapter'),
    path('series/', views.series, name="series"),
    path('profile/', views.profile, name="profile"),
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('comics/', views.adminComics, name="comics"),
    path('update_comic/<slug:slug>/', views.updateComic, name="update_comic"),
    path('<slug:post>/', views.comic, name='comic'),

]

rhixescans/urls.py
from django.urls import path, include
from django.contrib import admin
# from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
# from rest_framework.schemas import get_schema_view
# from rest_framework.documentation import include_docs_urls

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('Comics.urls', namespace='Comics')),
    # path('api/', include('blog_api.urls', namespace='blog_api')),
    # # API Token Management
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # # User Management

    # path('api/user/', include('users.urls', namespace='users')),
    # # Comics_API Application

    # Project URLs


    # # API schema and Documentation
    # path('docs/', include_docs_urls(title='Rhixescans')),
    # path('schema/', get_schema_view(
    #     title="Rhixescans",
    #     description="Manhwa and Manhua",
    #     version="1.0.0",
    # ), name='api-schema'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.MyTokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('login/refresh/', views.RefreshTokenObtainPairView.as_view(),
         name='refresh_token_obtain_pair'),
    path('create/', views.registerUser, name='register'),
    path('', views.getUsers, name="users"),
    path('profile/', views.getUserProfile, name="users-profile"),
    path('profile/update/', views.updateUserProfile, name="user-profile-update"),
    path('<str:pk>/', views.getUserById, name='user'),
    path('update/<str:pk>/', views.updateUser, name='user-update'),
    path('delete/<str:pk>/', views.deleteUser, name='user-delete'),
    path('logout/blacklist/', views.BlacklistTokenUpdateView.as_view(),
         name='blacklist')
]

templates/base/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
  <head>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" />
    <link rel="icon" href="{% static 'img/Logo.jpg' %}" />
    <link rel="stylesheet" href="{% static 'fws/all.css' %}" />
    <link rel="stylesheet" href="{% static 'fws/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Manhwa and Manhua" />
    <title>Rhixescans</title>
  
  </head>
  <body id="bg-img">
    {% include 'base/header.html' %}
    {% block content %}
    <!-- Content goes here -->
    {% endblock content %}
   
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'fws/bootstrap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

templates/base/footer.html
{% load static %} {% load crispy_forms_tags %}
<footer id="main-footer">
  <style>
    /* scroll up*/
    #btn-back-to-top {
      position: fixed;
      bottom: 20px;
      right: 20px;
      display: block;
    }
  </style>
  <p>Copyright &copy; 2023</p>
  <button
    type="button"
    class="btn btn-danger btn-floating btn-lg"
    id="btn-back-to-top"
  >
    <i class="fas fa-arrow-up"></i>
  </button>
</footer>
<script>
  //Get the button
  let mybutton = document.getElementById("btn-back-to-top");
  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function () {
    scrollFunction();
  };
  // Scroll function
  function scrollFunction() {
    if (
      document.body.scrollTop > 20 ||
      document.documentElement.scrollTop > 20
    ) {
      mybutton.style.display = "block";
    } else {
      mybutton.style.display = "none";
    }
  }
  // When the user clicks on the button, scroll to the top of the document
  mybutton.addEventListener("click", backToTop);
  function backToTop() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>

templates/base/header.html
{% load static %} {% load crispy_forms_tags %}
<header>
  <div class="menu-btn">
    <div class="btn-line"></div>
    <div class="btn-line"></div>
    <div class="btn-line"></div>
  </div>
  <nav class="menu">
    <div class="menu-branding">
      <a href="{% url 'Comics:index' %}">
        <div class="portrait"></div>
      </a>
    </div>
    <ul class="menu-nav">
      <li class="nav-item current">
        <a class="nav-link" href="{% url 'Comics:index' %}"> Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:series' %}">Series</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:register' %}">Register</a>
      </li>
      {% endif %} {% if request.user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Comics:comics' %}">Comics</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</header>
{% include 'base/messages.html' %}

templates/base/messages.html
{% load static %} {% load crispy_forms_tags %}
<ul class="messages">
  {% if messages %} {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %} {% endif %}
</ul>