Comics/urls.py
from django.urls import path
from . import views

app_name = 'Comics'

urlpatterns = [
    path('', views.index, name="index"),

    path('chapter/<str:str>/', views.chapter, name='chapter'),
    path('series/', views.series, name="series"),
    path('profile/', views.profile, name="profile"),
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('comics/', views.adminComics, name="comics"),
    path('update_comic/<slug:slug>/', views.updateComic, name="update_comic"),
    path('<slug:post>/', views.comic, name='comic'),

]

rhixescans/urls.py
from django.urls import path, include
from django.contrib import admin
# from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
# from rest_framework.schemas import get_schema_view
# from rest_framework.documentation import include_docs_urls

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('Comics.urls', namespace='Comics')),
    # path('api/', include('blog_api.urls', namespace='blog_api')),
    # # API Token Management
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # # User Management

    # path('api/user/', include('users.urls', namespace='users')),
    # # Comics_API Application

    # Project URLs


    # # API schema and Documentation
    # path('docs/', include_docs_urls(title='Rhixescans')),
    # path('schema/', get_schema_view(
    #     title="Rhixescans",
    #     description="Manhwa and Manhua",
    #     version="1.0.0",
    # ), name='api-schema'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.MyTokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('login/refresh/', views.RefreshTokenObtainPairView.as_view(),
         name='refresh_token_obtain_pair'),
    path('create/', views.registerUser, name='register'),
    path('', views.getUsers, name="users"),
    path('profile/', views.getUserProfile, name="users-profile"),
    path('profile/update/', views.updateUserProfile, name="user-profile-update"),
    path('<str:pk>/', views.getUserById, name='user'),
    path('update/<str:pk>/', views.updateUser, name='user-update'),
    path('delete/<str:pk>/', views.deleteUser, name='user-delete'),
    path('logout/blacklist/', views.BlacklistTokenUpdateView.as_view(),
         name='blacklist')
]

Comics/models.py
from django.db import models
from .managers import NewManager
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from io import BytesIO
from django.core import files
from requests_html import HTMLSession
from PIL import Image
from django.urls import reverse
# from django.db.models.signals import post_save
# from django.contrib.auth.models import User
# from django.dispatch import receiver
# from django.core.exceptions import ValidationError
# from django.core.files.images import get_image_dimensions


# def user_directory_path(instance, filename):
#     return 'users/avatars/{0}/{1}'.format(instance.user.id, filename)
s = HTMLSession()
headers = {
    'User-Agent': "Mozilla/5.0 (Windows NT x.y; Win64; x64; rv:10.0) Gecko/20100101 Firefox/10.0"
}


def comics_images_location(instance, filename):
    return '{}/{}'.format(str(instance.title).replace(" ", "_").replace(":", " ").replace("/", "").replace("\\", ""), filename)


def comics_chapters_images_location(instance, filename):
    return '{}/{}/{}'.format(str(instance.chapter.comic.title).replace(" ", "_").replace(":", " ").replace("/", "").replace("\\", ""),  instance.chapter.name, filename)


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     avatar = models.ImageField(
#         upload_to=user_directory_path, default='users/avatar.jpg')
#     bio = models.TextField(max_length=500, blank=True)

#     def clean(self):
#         if not self.avatar:
#             raise ValidationError("x")
#         else:
#             w, h = get_image_dimensions(self.avatar)
#             if w != 500:
#                 raise ValidationError("x")
#             if h != 500:
#                 raise ValidationError("x")

#     def __str__(self):
#         return self.user.username


# @ receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True, null=True)

    def __str__(self):
        return self.name


class Categorys(models.Model):
    name = models.CharField(max_length=100, unique=True, null=True)

    def __str__(self):
        return self.name


class Comic(models.Model):

    options = (
        ('Completed', 'Completed'),
        ('Ongoing', 'Ongoing'),
        ('Dropped', 'Dropped'),
        ('Coming Soon', 'Coming Soon'),
        ('Hiatus', 'Hiatus'),
    )

    title = models.CharField(max_length=1000, unique=True, null=True)
    alternativetitle = models.CharField(max_length=1000, blank=True, null=True)
    slug = models.SlugField(max_length=1000, unique_for_date='created')
    description = models.TextField(blank=True, null=True)
    # image = models.ImageField(
    #    upload_to=None, max_length=100000, default='placeholder.png', height_field=None, width_field=None)
    image_url = models.URLField(max_length=100000, null=True)
    image = models.ImageField(
        max_length=100000, upload_to=comics_images_location)

    rating = models.DecimalField(max_digits=9, decimal_places=1, blank=True)
    status = models.CharField(
        max_length=15, choices=options, default='Ongoing')
    author = models.CharField(max_length=100, blank=True, null=True)
    artist = models.CharField(max_length=100, blank=True, null=True)
    released = models.CharField(max_length=100, blank=True, null=True)
    serialization = models.CharField(max_length=1000, blank=True, null=True)
    numChapters = models.IntegerField(default=0, null=True, blank=True)
    numReviews = models.IntegerField(default=0, null=True, blank=True)
    genres = models.ManyToManyField(Genre, blank='True')
    category = models.ManyToManyField(Categorys)
    created_by = models.CharField(max_length=100, blank=True, null=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)
    favourites = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='favourite', blank=True,)
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like', blank=True)
    like_count = models.IntegerField(default=0, blank=True, null=True)
    objects = models.Manager()  # default manager
    newmanager = NewManager()

    def get_absolute_url(self):
        return reverse('Comics:comic', args=[self.slug])

    class Meta:
        ordering = ['updated']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.image == '' and self.image_url != '':
            resp = s.get(self.image_url,  stream=True, headers=headers)
            pb = BytesIO()
            pb.write(resp.content)
            pb.flush()
            # pb = Image.open(BytesIO(resp.content))
            file_name = self.image_url.split("/")[-1]
            self.image.save(file_name, files.File(pb),
                            save=True)
            return super().save(*args, **kwargs)
        else:
            return print(self.title)

    # def save(self, *args, **kwargs):

    #     if self.images == '' and self.image_urls != '':
    #         resp = s.get(self.image_urls,  stream=True, headers=headers)
    #         orig_image = Image.open(BytesIO(resp.content))
    #         file_name = self.image_urls.split("/")[-1]
    #         self.images.save(file_name, files.File(orig_image),
    #                          save=True)
    #         return super().save(*args, **kwargs)
    #     else:
    #         pass


class ExtraManagers(models.Model):
    secondary = NewManager()

    class Meta:
        abstract = True


class ComicsManager(Comic, ExtraManagers):

    objects = NewManager()

    class Meta:

        proxy = True

    def do_something(self):
        pass


class Chapter(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, null=True)
    readers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='reader')
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000, unique=True, null=True)
    pages = models.ManyToManyField('Page', blank=True, related_name='pages')
    rating = models.DecimalField(
        max_digits=9, decimal_places=1, null=True, blank=True)
    numReviews = models.IntegerField(default=0, null=True, blank=True)
    numPages = models.IntegerField(default=0, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('Comics:chapter', args=[self.name])

    class Meta:
        ordering = ['updated']

    def __str__(self):
        return self.name


class Page(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    image_urls = models.URLField(max_length=100000)
    images = models.ImageField(
        max_length=100000, upload_to=comics_chapters_images_location)
    # images = models.ImageField(
    #    upload_to=None, max_length=100000, height_field=None, width_field=None, null=True, blank=False)

    def __str__(self):
        return self.image_urls

    def save(self, *args, **kwargs):
        if self.images == '' and self.image_urls != '':

            resp = s.get(self.image_urls,  stream=True, headers=headers)
            pb = BytesIO()
            pb.write(resp.content)
            pb.flush()
            # pb = Image.open(BytesIO(resp.content))
            file_name = self.image_urls.split("/")[-1]
            self.images.save(file_name, files.File(pb),
                             save=True)
            return super().save(*args, **kwargs)
        else:
            return print(self.chapter.name)


class Review(models.Model):
    options = ((1, '1 - Trash'),
               (2, '2 - Horrible'),
               (3, '3 - Terrible'),
               (4, '4 - Bad'),
               (5, '5 - OK'),
               (6, '6 - Watchable'),
               (7, '7 - Good'),
               (8, '8 - Very Good'),
               (9, '9 - Perfect'),
               (10, '10 - Master Piece'),)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    chapter = models.ForeignKey(
        Chapter, on_delete=models.SET_NULL, null=True, related_name='comments')
    comic = models.ForeignKey(Comic, on_delete=models.SET_NULL, null=True)
    text = models.TextField(max_length=3000, null=False)
    rating = models.PositiveSmallIntegerField(
        choices=options, default=1)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['updated']

    def __str__(self):
        return self.text


class Likes(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_like')
    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name='review_like')
    likes = models.PositiveIntegerField(default=0)
    unlikes = models.PositiveIntegerField(default=0)

Comics/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import *
from users.models import NewUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = NewUser
        fields = ['user_name', 'email', 'first_name',
                  'about', 'avatar', 'password1', 'password2']


class ComicForm(ModelForm):
    class Meta:
        model = Comic
        fields = '__all__'

        widgets = {
            'genres': forms.CheckboxSelectMultiple(),
            'category': forms.CheckboxInput(),
        }


class ChapterForm(ModelForm):
    class Meta:
        model = Chapter
        fields = '__all__'

        widgets = {
            'pages': forms.CheckboxSelectMultiple(),

        }

Comics/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from users.models import NewUser
from .forms import *
from django.contrib.auth.decorators import login_required


def index(request):
    posts = Comic.objects.all()
    comics = Comic.newmanager.filter(rating__gte=10.0).order_by('-title')
    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 21)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'comics': comics}
    return render(request, 'Comics/index.html', context)


def series(request):
    posts = Comic.objects.all()
    comics = Comic.newmanager.filter(rating__gte=10.0).order_by('-title')
    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 21)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'comics': comics}
    return render(request, 'Comics/series.html', context)


@login_required(login_url="Comics:index")
def comic(request, post):
    post = get_object_or_404(Comic, slug=post)
    chapters = post.chapter_set.all().order_by('-name')
    context = {'post': post, 'chapters': chapters}
    return render(request, 'Comics/comic.html', context)


@login_required(login_url="Comics:index")
def chapter(request, str):
    post = get_object_or_404(Chapter, name=str)
    pages = post.pages.all()
    chapters = post.comic.chapter_set.all().order_by('-name')
    context = {'post': post, 'pages': pages, 'chapters': chapters}
    return render(request, 'Comics/chapter.html', context)


@login_required(login_url="Comics:index")
def profile(request):
    user = request.user
    context = {'user': user}
    return render(request, 'Comics/profile.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('Comics:index')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Little Hack to work around re-building the usermodel
        try:
            user = NewUser.objects.get(email=email)
            user = authenticate(
                request, email=user.email,  password=password)
        except:
            messages.error(request, 'User with this email does not exists')
            return redirect('Comics:login')

        if user is not None:
            login(request, user)
            return redirect('Comics:index')
        else:
            messages.error(request, 'Email OR password is incorrect')

    context = {}
    return render(request, 'Comics/login.html', context)


def registerPage(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, 'Account successfuly created!')

            user = authenticate(request, email=user.email,
                                password=request.POST['password1'])

            if user is not None:
                login(request, user)

            next_url = request.GET.get('next')
            if next_url == '' or next_url == None:
                next_url = 'Comics:index'
            return redirect(next_url)
        else:
            messages.error(request, 'An error has occured with registration')
    context = {'form': form}
    return render(request, 'Comics/register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('Comics:index')


@login_required(login_url="Comics:index")
def adminComics(request):

    posts = Comic.objects.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 21)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts}
    return render(request, 'Comics/adminComics.html', context)


@login_required(login_url="Comics:index")
def updateComic(request, slug):
    post = Comic.objects.get(slug=slug)
    form = ComicForm(instance=post)

    if request.method == 'POST':
        form = ComicForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('Comics:comics')

    context = {'form': form}
    return render(request, 'Comics/comic_form.html', context)

templates/Comics/Comics_feed.html
{% load static %}
<div>
  <h2 class="sm-heading">Recent Comics</h2>
  {% for comic in posts %}
  <div class="card">
    <a href="{{comic.get_absolute_url}}">
      <img
        src="{{comic.image.url}}"
        class="card-img-top"
        alt="{{comic.title}}"
      />
    </a>

    <div class="card-body">
      <a href="{{comic.get_absolute_url}}">
        <h3 class="card-title">{{comic.title}}</h3>
      </a>

      <p class="card-text">{{comic.description}}</p>
      <a href="{{comic.get_absolute_url}}" class="btn btn-primary">View</a>
    </div>
  </div>
  {% empty %}
  <h1>No Comics</h1>
  {% endfor %}
  <nav aria-label="posts">
    {% if posts.has_other_pages %}
    <ul class="pagination justify-content-center">
      {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{posts.previous_page_number}}"
          >Previous</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
      {% endif %}

      <!-- {% for i in posts.paginator.page_range %} 
        {% if posts.number == i %}
        <li class="page-item"><a class="active page-link">{{i}}</a></li>
        {% else %}
        <li class="page-item">
          <a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a>
        </li>
        {% endif %} {% endfor %} -->

      {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{posts.next_page_number}}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
</div>

templates/Comics/adminComics.html
{% extends 'base/base.html' %}{% load static %} {% block content %}
<main id="adminComics">
  {% load crispy_forms_tags %}
  <h1>Admin Comics</h1>
  <table class="table table-dark table-sm">
    <thead class="thead">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>

        <th scope="col">Chapters</th>
        <th scope="col">Genres</th>
        <th scope="col">Categorys</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for comic in posts %}
      <tr>
        <td>{{comic.id }}</td>
        <td>
          <a href="{{comic.get_absolute_url}}"> {{comic.title}} </a>
        </td>

        <td>
          {% for chapter in comic.chapter_set.all %}
          <div>
            <a href="{{chapter.get_absolute_url}}"> {{chapter.name}} </a>
          </div>
          {% empty %}
          <small>No Chapters</small>
          {% endfor %}
        </td>
        <td>
          {% for genre in comic.genres.all %}
          <div>{{genre.name}}</div>
          {% endfor %}
        </td>
        <td>
          {% for cat in comic.category.all %}
          <div>{{cat.name}}</div>
          {% endfor %}
        </td>
        <td>
          <a href="{% url 'Comics:update_comic' comic.slug %}">Edit</a>
        </td>
        <td>
          <a href="#">Delete</a>
        </td>
      </tr>
      {% empty %}
      <small>No Comics</small>
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="posts">
    {% if posts.has_other_pages %}
    <ul class="pagination justify-content-center">
      {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{posts.previous_page_number}}"
          >Previous</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
      {% endif %} {% for i in posts.paginator.page_range %} {% if posts.number == i %}
      <li class="page-item"><a class="active page-link">{{i}}</a></li>
      {% else %}
      <li class="page-item">
        <a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a>
      </li>
      {% endif %} {% endfor %} {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{posts.next_page_number}}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
</main>
{% include 'base/footer.html' %} {% endblock content %}

templates/Comics/chapter.html
{% extends 'base/base.html' %}{% load static %} {% block content %}
<main id="chapter">
  {% load crispy_forms_tags %}
  <div class="chapters">
    <div class="item">
      <nav>
        <ul>
          <li>
            <a class="btn-light" href="{{post.comic.get_absolute_url}}">
              {{post.comic.title}}
            </a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              data-bs-toggle="dropdown"
              href="{{post.get_absolute_url}}"
              role="button"
              aria-expanded="false"
              >{{post.name}}</a
            >

            <ul class="dropdown-menu">
              {% for chapter in chapters %}
              <li>
                <a class="dropdown-item" href="{{chapter.get_absolute_url}}"
                  >{{chapter.name}}</a
                >
              </li>

              <li><hr class="dropdown-divider" /></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </nav>
    </div>
    {% for page in pages %}
    <div class="item">
      <img src="{{page.images.url}}" alt="{{page.chapter.name}}" />
    </div>
    {% empty %}
    <small>no Page</small>
    {% endfor %}
    <div class="item">
      <nav>
        <ul>
          <li>
            <a class="btn-light" href="{{post.comic.get_absolute_url}}">
              {{post.comic.title}}
            </a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="btn-dark nav-link dropdown-toggle"
              data-bs-toggle="dropdown"
              href="{{post.get_absolute_url}}"
              role="button"
              aria-expanded="false"
              >{{post.name}}</a
            >

            <ul class="dropdown-menu">
              {% for chapter in chapters %}
              <li>
                <a
                  class="btn-dark dropdown-item"
                  href="{{chapter.get_absolute_url}}"
                  >{{chapter.name}}</a
                >
              </li>

              <li><hr class="dropdown-divider" /></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</main>
{% include 'base/footer.html' %} {% endblock content %}

templates/Comics/comic.html
{% extends 'base/base.html' %} {% load static %}{% block content %}
<main id="comic">
  {% load crispy_forms_tags %}
  <div class="comic-info">
    <div>
      <img class="comic-image" src="{{post.image.url}}" alt="{{post.title}}" />
    </div>

    <div class="bio">

      <div>
        <b class="textsecondary">Title:</b>
          <h2>{{post.title}}</h2>
      </div>
      <ul>
        <li>
          <b class="textsecondary">Alternativetitle:</b>
            <span>{{post.alternativetitle}}</span></li>
        </ul>
        <li>
          <b class="textsecondary">Description:</b>
            <span>{{post.description}}</span></li>
        </li>
        <li>
          <b class="textsecondary">Author:</b>
            <span>{{post.author}}</span></li>
        </li>
        <li>
          <b class="textsecondary">Artist:</b>
            <span>{{post.artist}}</span></li>
        </li>
        <li>
          <b class="textsecondary">Status:</b>
            <span>{{post.status}}</span></li>
        </li>
        <li>
          <b class="textsecondary">Rating:</b>
            <span>{{post.rating}}</span></li>
        </li>
        <li>
          <b class="textsecondary">Created_by:</b>
            <span>{{post.created_by}}</span></li>
        </li>
      </ul>
    </div>
     
    <div>
      <ul>
        {% for chapter in chapters %}
        <li class="job">
          <a href="{{chapter.get_absolute_url}}">{{chapter.name}}</a>
        </li>
        {% empty %}
        <small>No Chapters</small>
        {% endfor %}
      </ul>
    </div>
  </div>
</main>
{% include 'base/footer.html' %} {% endblock content %}

templates/Comics/comic_form.html
{% extends 'base/base.html' %}{% load static %} {% block content %}
<main id="comic-form">
  {% load crispy_forms_tags %}
  <div class="container">
    <a class="btn btn-sm btn-primary" href="{% url 'Comics:comics' %}"
      >&laquo Back to Home</a
    >
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{form.media}} {{form|crispy}}
      <input class="btn btn-primary" type="submit" value="Submit Comic" />
    </form>
  </div>
</main>
{% include 'base/footer.html' %} {% endblock content %}

templates/Comics/index.html
{% extends 'base/base.html' %} {% load static %}{% block content %}
<main id="home">
  {% load crispy_forms_tags %}
  <div>
    <h1 class="lg-heading">Top <span class="textsecondary">Comics</span></h1>
    <div id="carouselExample" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="" alt="" />
        </div>
        {% for comic in comics %}
        <div class="carousel-item">
          <a href="{{comic.get_absolute_url}}">
            <img src="{{comic.image.url}}" alt="{{comic.title}}" />
          </a>
        </div>
        {% empty %}
        <h1>No Comics</h1>
        {% endfor %}
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExample"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExample"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <br />
  {% include 'Comics/Comics_feed.html' %}
  <div class="icons">
    <a href="#!">
      <i class="fab fa-twitter fa-2x"></i>
    </a>
    <a href="#!">
      <i class="fab fa-facebook fa-2x"></i>
    </a>
    <a href="#!">
      <i class="fab fa-linkedin fa-2x"></i>
    </a>
    <a href="#!">
      <i class="fab fa-github fa-2x"></i>
    </a>
  </div>
</main>
{% endblock content %}

templates/Comics/login.html
{% extends 'base/base.html' %}{% load static %} {% block content %}
<main id="login">
  {% load crispy_forms_tags %} {% if messages %} {% for message in messages %}
  {% if message.tags == 'success' %}
  <div class="alert alert-success" role="alert">
    <span>{{message}}</span>
  </div>
  {% elif message.tags == 'error' %}
  <div class="alert alert-danger" role="alert">
    <span>{{message}}</span>
  </div>
  {% endif %} {% endfor %} {% endif %}
  <h3>Login</h3>
  <hr />
  <form method="POST">
    {% csrf_token %} {{form|crispy}}
    <label>Email</label>
    <input class="form-control" type="email" name="email" />
    <br />
    <label>Password</label>
    <input class="form-control" type="password" name="password" />
    <br />
    <input
      class="btn btn-primary btn-lg btn-block"
      type="submit"
      value="Login"
    />
  </form>

  <br />
  <p>
    Dont have an account? <a href="{% url 'Comics:register' %}">Register</a>
  </p>
  <p>Forgot your password? <a href="#">Reset</a></p>
</main>
{% include 'base/footer.html' %} {% endblock content %}